security:
    hide_user_not_found:  false
  #  encoders:
  #      Symfony\Component\Security\Core\User\User: plaintext
    encoders:
        Application\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        chain:
#            providers: [in_memory, users_db]
#        in_memory:
#            users:
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users_db:
            entity: { class: Application\UserBundle\Entity\User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                use_referer: true
            anonymous: ~
            logout:
                path:   /logout
                target: /login
            
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }