<?php

namespace Application\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends EntityRepository
{
    
    /**
     * 
     * @param \Bundle\UserBundle\Entity\Upload $upload
     */
    public function save(Upload $upload){
       $this->getEntityManager()->persist($upload);
       $this->getEntityManager()->flush();
    }
}
